package com.analyzercoder.infrastructure.persistence.mapper;
import com.analyzercoder.infrastructure.persistence.model.KnowledgeCardRow;import java.util.*;import org.apache.ibatis.annotations.*;
@Mapper public interface IntelligenceMapper{
List<Map<String,Object>> search(@Param("repositoryId")UUID repositoryId,@Param("query")String query,@Param("vector")String vector,@Param("limit")int limit);
int insertConversation(@Param("id")UUID id,@Param("repositoryId")UUID repositoryId,@Param("accountId")UUID accountId,@Param("question")String question,@Param("answer")String answer,@Param("snapshotId")UUID snapshotId);
int insertCitation(@Param("id")UUID id,@Param("conversationId")UUID conversationId,@Param("chunkId")UUID chunkId,@Param("filePath")String filePath,@Param("symbolName")String symbolName,@Param("startLine")Integer startLine,@Param("endLine")Integer endLine,@Param("evidenceHash")String evidenceHash,@Param("rank")int rank);
List<Map<String,Object>> graphEdges(@Param("repositoryId")UUID repositoryId);int deleteGraphEdges(@Param("repositoryId")UUID repositoryId);List<Map<String,Object>> graphChunks(@Param("repositoryId")UUID repositoryId);int insertGraphEdge(@Param("id")UUID id,@Param("repositoryId")UUID repositoryId,@Param("snapshotId")UUID snapshotId,@Param("sourceChunkId")UUID sourceChunkId,@Param("targetChunkId")UUID targetChunkId,@Param("sourceSymbol")String sourceSymbol,@Param("targetSymbol")String targetSymbol);
List<KnowledgeCardRow> cards(@Param("repositoryId")UUID repositoryId,@Param("includeDraft")boolean includeDraft);int insertCard(@Param("id")UUID id,@Param("repositoryId")UUID repositoryId,@Param("actorId")UUID actorId,@Param("title")String title,@Param("cardType")String cardType,@Param("content")String content,@Param("tags")String[] tags,@Param("status")String status);int updateCard(@Param("id")UUID id,@Param("repositoryId")UUID repositoryId,@Param("actorId")UUID actorId,@Param("title")String title,@Param("cardType")String cardType,@Param("content")String content,@Param("tags")String[] tags,@Param("status")String status);
List<Map<String,Object>> settings();int upsertSetting(@Param("key")String key,@Param("value")String value,@Param("actorId")UUID actorId);
List<Map<String,Object>> backups();List<Map<String,Object>> backupKnowledge();List<Map<String,Object>> backupRepositories();List<Map<String,Object>> backupAccounts();int insertBackup(@Param("id")UUID id,@Param("manifest")String manifest,@Param("checksum")String checksum,@Param("actorId")UUID actorId);String backupManifest(@Param("id")UUID id);String backupChecksum(@Param("id")UUID id);int clearSessions();int markRestored(@Param("id")UUID id);
List<Map<String,Object>> missingEmbeddings(@Param("repositoryId")UUID repositoryId);int upsertEmbedding(@Param("chunkId")UUID chunkId,@Param("repositoryId")UUID repositoryId,@Param("vector")String vector,@Param("contentHash")String contentHash);
}
