const { chromium } = require(process.env.QA_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const out = process.env.QA_OUTPUT || path.join(__dirname, 'results');
const url = process.env.QA_URL || 'http://127.0.0.1:5173/qa/ui-optimization.html';
let browser, current;
if (!['127.0.0.1', 'localhost', '[::1]'].includes(new URL(url).hostname) || !new URL(url).pathname.endsWith('/qa/ui-optimization.html')) throw new Error('QA_URL must point to the local UI fixture.');
const results=[];
async function fresh(route='knowledge',width=1366,params='') {
 const p=await browser.newPage({viewport:{width,height:width===390?844:width===1440?900:768}});current=p;p.setDefaultTimeout(12000);p.errors=[];
 p.on('pageerror',e=>p.errors.push(e.message));
 await p.context().route(new URL('/api/**',url).href,r=>r.fulfill({status:200,contentType:'text/plain',headers:{'Content-Disposition':'attachment; filename="qa.txt"'},body:'QA attachment'}));
 await p.goto(`${url}${params}#/${route}`);await p.locator('#app > *').first().waitFor();await p.waitForTimeout(400);return p;
}
async function branch(p,name){await p.locator('.global-branch-switcher .el-select__wrapper').click();await p.getByRole('option',{name:name+' · 可用',exact:true}).click();}
const row=(p,id)=>p.locator(`[data-card-id="${id}"]`);
const shot=async(p,name)=>p.screenshot({path:path.join(out,name+'.png'),fullPage:!await p.locator('[role=dialog]:visible').count(),animations:'disabled'});
async function closeDrawer(p){await p.locator('.knowledge-reader .el-drawer__close-btn').click();await p.locator('.knowledge-reader').waitFor({state:'hidden'});}
async function check(name,run){if(process.env.QA_MATCH && !name.includes(process.env.QA_MATCH))return;try{await run();assert.deepEqual(current.errors,[]);results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message,errors:current?.errors});if(current)await shot(current,'failure-'+results.length).catch(()=>{});console.log('FAIL',name,e.message);}finally{for(const c of browser.contexts())await c.close();}}
(async()=>{
 await fs.mkdir(out,{recursive:true});browser=await chromium.launch({channel:process.env.QA_BROWSER_CHANNEL||'msedge',headless:true});
 await check('知识筛选、详情焦点、跨分支源码往返',async()=>{
  const p=await fresh();await row(p,'card-1').waitFor();await p.getByPlaceholder('搜索标题、正文或标签').fill('退款');
  await row(p,'card-1').getByRole('button',{name:'+2',exact:true}).click();assert.match(await row(p,'card-1').innerText(),/审计/);
  const trigger=row(p,'card-1').getByRole('button',{name:'查看',exact:true});await trigger.click();await p.locator('.knowledge-reader').waitFor();await closeDrawer(p);assert.equal(await trigger.evaluate(el=>el===document.activeElement),true);
  await trigger.click();await p.locator('.knowledge-reader').getByRole('button',{name:'查看源码',exact:true}).click();await p.waitForURL(/#\/search/);await p.locator('.file-code-line.focused').first().waitFor();assert.match(await p.locator('.file-facts').innerText(),/legacy/);
  await p.goBack();await p.waitForURL(/#\/knowledge/);await p.locator('.knowledge-reader').waitFor();assert.equal(await p.getByPlaceholder('搜索标题、正文或标签').inputValue(),'退款');await p.locator('.knowledge-reader').getByText('已发布 · 当前分支已验证',{exact:true}).waitFor();await shot(p,'after-knowledge-roundtrip-1366');
 });
 await check('知识必填校验、预览、上传、保存、发布、历史恢复',async()=>{
  const p=await fresh();await p.getByRole('button',{name:'新建卡片',exact:true}).click();const d=p.getByRole('dialog',{name:'新建知识卡片'});await d.getByRole('button',{name:'创建草稿',exact:true}).click();await d.getByText('请填写标题',{exact:true}).waitFor();await d.getByText('请填写知识正文',{exact:true}).waitFor();
  await d.getByPlaceholder('一句话说明这条知识').fill('验收新增知识');await d.getByRole('textbox',{name:'知识正文',exact:true}).fill('验收正文 **保留输入**');await d.getByText('项目共享（所有分支）',{exact:true}).click();
  await d.getByRole('button',{name:'预览',exact:true}).click();await d.getByText('保留输入',{exact:true}).waitFor();await d.getByRole('button',{name:'编写',exact:true}).click();
  await d.locator('.attachment-details summary').click();await d.locator('input[type=file]').setInputFiles({name:'qa.txt',mimeType:'text/plain',buffer:Buffer.from('QA attachment')});await d.getByText('qa.txt',{exact:true}).waitFor();await shot(p,'after-editor-1366');await d.getByRole('button',{name:'创建草稿',exact:true}).click();await d.waitFor({state:'hidden'});
  const item=p.locator('.knowledge-card').filter({has:p.getByRole('button',{name:'验收新增知识',exact:true})});await item.waitFor();await item.getByRole('button',{name:'确认并发布',exact:true}).click();await p.locator('.el-message-box').getByRole('button',{name:'确认并发布',exact:true}).click();await item.getByText('已发布 · 尚无当前分支验证',{exact:true}).waitFor();
  await item.getByRole('button',{name:'编辑',exact:true}).click();const edit=p.getByRole('dialog',{name:'编辑知识卡片'});await edit.getByRole('textbox',{name:'知识正文',exact:true}).fill('第二版正文');assert.match(await edit.innerText(),/附件 · 1 个/);await edit.getByRole('button',{name:'保存新修订',exact:true}).click();await edit.waitFor({state:'hidden'});
  await item.getByRole('button',{name:'更多知识操作'}).click();await p.getByRole('menuitem',{name:'修订历史',exact:true}).click();const history=p.getByRole('dialog',{name:/修订历史/});await history.waitFor();await history.getByRole('button',{name:'恢复为新草稿',exact:true}).first().click();await p.locator('.el-message-box__btns button').last().click();await history.waitFor({state:'hidden'});
  await item.getByRole('button',{name:'查看',exact:true}).click();await p.locator('.knowledge-reader').getByText('保留输入',{exact:true}).waitFor();await p.locator('.knowledge-reader').getByText('qa.txt',{exact:true}).waitFor();
  const download=await Promise.all([p.waitForEvent('download'),p.locator('.knowledge-reader').getByRole('link',{name:'下载',exact:true}).click()]);assert.equal(download[0].suggestedFilename(),'qa.txt');
  const calls=await p.evaluate(()=>window.__uiQa.calls.filter(c=>c.body?.title==='验收新增知识'));assert.equal(calls[0].body.branchScope.mode,'ALL_BRANCHES');assert.equal(calls[0].body.attachmentIds.length,1);await shot(p,'after-restored-knowledge-1366');
 });
 await check('知识修订冲突保留输入及引用标识',async()=>{
  const p=await fresh();await row(p,'card-1').getByRole('button',{name:'编辑',exact:true}).click();const d=p.getByRole('dialog',{name:'编辑知识卡片'});await d.getByPlaceholder('一句话说明这条知识').fill('冲突测试');await d.getByRole('textbox',{name:'知识正文',exact:true}).fill('冲突后保留正文');await d.getByRole('button',{name:'保存新修订',exact:true}).click();await d.getByRole('alert').waitFor();assert.equal(await d.getByRole('textbox',{name:'知识正文',exact:true}).inputValue(),'冲突后保留正文');assert.match(await d.innerText(),/当前输入保留/);
  const call=await p.evaluate(()=>window.__uiQa.calls.find(c=>c.body?.title==='冲突测试'));assert.deepEqual(call.body.codeReferences,[{chunkId:'chunk-1'}]);assert.deepEqual(call.body.branchScope.branchIds,['main','legacy']);assert.equal(call.body.expectedRevision,1);await shot(p,'after-save-conflict-1366');
 });
 await check('源码检索高亮、失败重试、无结果、证据并排',async()=>{
  const p=await fresh('search');await p.locator('.file-code-lines').waitFor();await p.evaluate(()=>window.__uiQa.failNextSearch=true);await p.getByPlaceholder('搜索代码、设计说明、业务知识或文件路径').fill('退款');await p.getByRole('button',{name:'检索',exact:true}).click();await p.getByRole('button',{name:'重试检索'}).click();await p.locator('.search-hit-list > button').first().waitFor();assert.ok(await p.locator('.search-hit-list mark').count()>0);
  await p.locator('.search-hit-list > button').first().click();await p.locator('.file-code-line.focused').first().waitFor();await p.getByRole('button',{name:'文件关联证据',exact:true}).click();await p.locator('.workbench-evidence').waitFor();const a=await p.locator('.workbench-preview').boundingBox(),b=await p.locator('.workbench-evidence').boundingBox();assert.ok(a.width>=300&&b.x>=a.x+a.width-1);await p.getByRole('slider',{name:'证据区域宽度'}).fill('42');assert.ok((await p.locator('.context-title b').boundingBox()).height<30);await shot(p,'after-source-evidence-1366');
  await p.evaluate(()=>window.__uiQa.emptySearch=true);await p.getByRole('button',{name:'检索',exact:true}).click();await p.getByText('未找到匹配内容，可调整关键词或筛选条件',{exact:true}).waitFor();
 });
 await check('问答失败保留、重试、引用展开及源码往返',async()=>{
  const p=await fresh('ask');const input=p.getByRole('textbox',{name:'问题',exact:true});await input.waitFor();await p.evaluate(()=>window.__uiQa.failNextAsk=true);await input.fill('退款金额的边界是什么？');await p.getByRole('button',{name:'发送问题'}).click();await p.getByRole('button',{name:'重新发送',exact:true}).waitFor();assert.equal(await input.inputValue(),'退款金额的边界是什么？');await p.getByRole('button',{name:'重新发送',exact:true}).click();await p.locator('.answer-evidence summary').waitFor();assert.match(await p.locator('.assistant-content').innerText(),/未生成模型推理/);await p.locator('.answer-evidence summary').click();
  await p.locator('.answer-evidence').getByRole('button',{name:'查看源码',exact:true}).click();await p.waitForURL(/#\/search/);await p.locator('.file-code-line.focused').first().waitFor();await p.goBack();await p.waitForURL(/#\/ask/);assert.equal(await p.locator('.answer-evidence').getAttribute('open'),'');await shot(p,'after-ask-roundtrip-1366');
 });
 await check('当前分支范围、跨分支验证与独立状态',async()=>{
  const p=await fresh();await p.getByRole('button',{name:'新建卡片',exact:true}).click();const d=p.getByRole('dialog',{name:'新建知识卡片'});await d.getByPlaceholder('一句话说明这条知识').fill('仅 main 的知识');await d.getByRole('textbox',{name:'知识正文',exact:true}).fill('当前分支专属内容');await d.getByRole('button',{name:'创建草稿',exact:true}).click();await d.waitFor({state:'hidden'});
  const item=p.locator('.knowledge-card').filter({has:p.getByRole('button',{name:'仅 main 的知识',exact:true})});await item.getByText('仅 main 可见',{exact:true}).waitFor();const call=await p.evaluate(()=>window.__uiQa.calls.find(c=>c.body?.title==='仅 main 的知识'));assert.deepEqual(call.body.branchScope,{mode:'SELECTED_BRANCHES',branchIds:['main']});
  await branch(p,'legacy');await row(p,'card-1').getByText('已发布 · 当前分支不适用',{exact:true}).waitFor();assert.equal(await item.count(),0);await row(p,'card-1').getByRole('button',{name:'查看',exact:true}).click();await p.locator('.validation-panel[open]').waitFor();await p.locator('.validation-body .el-select__wrapper').click();await p.getByRole('option',{name:'已验证',exact:true}).click();await p.getByRole('textbox',{name:'验证说明',exact:true}).fill('已核对 legacy 的金额边界');await p.getByRole('button',{name:'保存验证结果',exact:true}).click();await p.locator('.knowledge-reader').getByText('已发布 · 当前分支已验证',{exact:true}).waitFor();await shot(p,'after-branch-validation-1366');await closeDrawer(p);
  await row(p,'card-1').getByText('已发布 · 当前分支已验证',{exact:true}).waitFor();await branch(p,'main');await item.waitFor();await row(p,'card-1').getByText('已发布 · 当前分支已验证',{exact:true}).waitFor();const validation=await p.evaluate(()=>window.__uiQa.calls.find(c=>c.path.endsWith('/branch-validation')));assert.equal(validation.body.contextId,'ctx-legacy');assert.equal(validation.body.state,'CURRENT');
 });
 await check('Markdown 来源查看、返回和生成草稿',async()=>{
  const p=await fresh();await p.getByRole('tab',{name:/Markdown 预备知识/}).click();await p.getByRole('button',{name:'查看 Markdown',exact:true}).click();await p.waitForURL(/#\/search/);await p.locator('.file-title').getByText('docs/refund.md',{exact:true}).waitFor();await p.goBack();await p.waitForURL(/#\/knowledge/);await p.getByRole('button',{name:'生成知识卡片',exact:true}).click();await p.getByRole('button',{name:'查看卡片',exact:true}).click();await p.locator('.knowledge-reader').getByText('先核对金额，再确认审批记录。',{exact:true}).waitFor();assert.match(await p.locator('.knowledge-reader').innerText(),/草稿/);await shot(p,'after-markdown-generated-1366');
 });
 await check('账号更多操作与审计跨账号定位',async()=>{
  const p=await fresh('accounts',1366,'?admin');await p.getByRole('button',{name:'模拟验收的更多操作'}).click();await p.getByRole('menuitem',{name:'访问令牌',exact:true}).waitFor();assert.equal(await p.getByRole('menuitem',{name:'停用账号',exact:true}).getAttribute('aria-disabled'),'true');await p.keyboard.press('Escape');await p.locator('.el-table__row').first().getByRole('button',{name:'查看审计',exact:true}).click();await p.getByText('已从账号列表定位：qa',{exact:true}).waitFor();
  await p.locator('a[href="#/accounts"]').first().click();await p.locator('.el-table__row').last().getByRole('button',{name:'查看审计',exact:true}).click();await p.getByText('已从账号列表定位：reader',{exact:true}).waitFor();assert.equal(await p.locator('.audit-table-region .el-table__row').count(),1);await p.locator('.el-table__expand-icon').click();await p.locator('.audit-event-detail').waitFor();assert.match(await p.locator('.audit-event-detail').innerText(),/qa-request-1/);await shot(p,'after-audit-focused-1366');
 });
 await check('模型检测、失败输入保留与成功重试',async()=>{
  const p=await fresh('settings',1366,'?admin');await p.getByRole('button',{name:'检测',exact:true}).click();await p.getByText('连接检测通过',{exact:true}).waitFor();await p.getByRole('button',{name:'新增模型',exact:true}).click();const d=p.getByRole('dialog',{name:'新增问答模型'});await d.getByPlaceholder('例如：生产问答模型').fill('新验收模型');await d.getByPlaceholder('https://llm.example.com/v1').fill('https://example.invalid/v1');await d.getByPlaceholder('model-name').fill('qa-model');await d.getByPlaceholder('可选',{exact:true}).fill('test-only-key');await p.evaluate(()=>window.__uiQa.failNextModelSave=true);await d.getByRole('button',{name:'保存备案',exact:true}).click();await d.getByText('模拟模型保存失败',{exact:true}).waitFor();assert.equal(await d.getByPlaceholder('可选',{exact:true}).inputValue(),'test-only-key');await shot(p,'after-model-save-error-1366');await d.getByRole('button',{name:'保存备案',exact:true}).click();await d.waitFor({state:'hidden'});await p.getByText('新验收模型',{exact:true}).waitFor();
 });
 await check('任务失败详情与对应分支管理入口',async()=>{
  const p=await fresh('indexing',1366,'?admin');await p.getByRole('combobox',{name:'任务所属分支'}).selectOption('legacy');await p.locator('.branch-task-table').getByText('失败',{exact:true}).waitFor();await p.locator('.branch-task-table').getByRole('button',{name:'查看',exact:true}).click();const d=p.getByRole('dialog',{name:'分支任务详情'});await d.getByText('模拟图谱构建失败，请检查任务详情。',{exact:true}).waitFor();await shot(p,'after-task-failure-1366');await d.getByRole('button',{name:'前往分支管理',exact:true}).click();await p.waitForURL(/#\/repositories/);await p.getByRole('region',{name:'分支管理'}).waitFor();assert.match(p.url(),/branchId=legacy/);
 });
 await check('图谱节点、关联、源码摘录和原行跳转',async()=>{
  const p=await fresh('atlas');await p.locator('[data-node]').first().click();await p.getByRole('button',{name:'关联出处',exact:true}).click();await p.locator('.relation-row').waitFor();await p.locator('.drawer-tabs').getByRole('button',{name:'源码',exact:true}).click();await p.locator('.atlas-source .marked').first().waitFor();await shot(p,'after-atlas-source-1366');await p.getByRole('button',{name:'打开文件',exact:true}).click();await p.waitForURL(/#\/search/);await p.locator('.file-code-line.focused').first().waitFor();assert.match(p.url(),/startLine=4/);
 });
 for(const width of [1440,1366,1024,390])await check(`响应式和键盘 ${width}`,async()=>{
  const p=await fresh('knowledge',width);await row(p,'card-1').waitFor();await shot(p,`after-knowledge-${width}`);await row(p,'card-1').getByRole('button',{name:'编辑',exact:true}).click();const d=p.getByRole('dialog',{name:'编辑知识卡片'});await d.waitFor();await shot(p,`after-editor-${width}`);const b=await d.getByRole('button',{name:'保存新修订',exact:true}).boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width&&b.y+b.height<=p.viewportSize().height);await p.keyboard.press('Escape');await d.waitFor({state:'hidden'});
  await p.goto(`${url}#/search`);await p.locator('.file-code-lines').waitFor({state:'attached'});if(width===390){await p.locator('.mobile-pane-switch').getByRole('button',{name:'证据',exact:true}).click();await p.locator('.workbench-evidence').waitFor();assert.equal(await p.locator('.workbench-grid').getAttribute('data-mobile-pane'),'context');await shot(p,'after-evidence-390');await p.locator('.mobile-pane-switch').getByRole('button',{name:'目录',exact:true}).click();await p.locator('.workbench-tree').waitFor();}
  await p.goto(`${url}#/ask`);await p.getByRole('textbox',{name:'问题',exact:true}).waitFor();await shot(p,`after-ask-${width}`);if(width===390)assert.ok((await p.locator('.scope-copy strong').boundingBox()).width>=200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await p.goto(`${url}#/overview`);await p.locator('.overview-sheet').waitFor();await shot(p,`after-overview-${width}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 });
 await check('键盘筛选、Tab 到查看、Enter 打开与 Escape 返回',async()=>{
  const p=await fresh();await row(p,'card-1').waitFor();await p.getByPlaceholder('搜索标题、正文或标签').focus();await p.keyboard.insertText('退款');const trigger=row(p,'card-1').getByRole('button',{name:'查看',exact:true});let reached=false;
  for(let i=0;i<24;i++){await p.keyboard.press('Tab');if(await trigger.evaluate(el=>el===document.activeElement)){reached=true;break;}}
  assert.ok(reached,'Tab must reach the filtered card view action');await p.keyboard.press('Enter');await p.locator('.knowledge-reader').waitFor();await p.keyboard.press('Escape');await p.locator('.knowledge-reader').waitFor({state:'hidden'});assert.equal(await trigger.evaluate(el=>el===document.activeElement),true);
 });
 await check('只读权限保留查看入口',async()=>{const p=await fresh('knowledge',1366,'?readonly');await row(p,'card-1').waitFor();assert.equal(await p.getByRole('button',{name:'新建卡片',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'编辑',exact:true}).count(),0);await row(p,'card-1').getByRole('button',{name:'查看',exact:true}).click();await p.locator('.knowledge-reader').waitFor();});
 await fs.writeFile(path.join(out,process.env.QA_MATCH ? 'interaction-partial.json' : 'interaction-results.json'),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
