export type IndexJobType='FULL'|'INCREMENTAL';
export type IndexJobStatus='QUEUED'|'RUNNING'|'CANCEL_REQUESTED'|'SUCCEEDED'|'FAILED'|'CANCELED';
export type ChunkType='FILE'|'SYMBOL'|'DOC_SECTION'|'TEST_CASE'|'CONFIG'|'KNOWLEDGE_CARD';
export interface ApiErrorResponse{code:string;message:string;timestamp:string}
export type RepositorySourceType='LOCAL_GIT'|'REMOTE_GIT'|'GITLAB'|'ZIP';
export interface RepositoryCapabilities{canRead:boolean;canUpdate:boolean;canIndex:boolean;canBuildCodeGraph:boolean;canConfigure:boolean;canGrant:boolean;canManageCredential:boolean;canTransferOwnership:boolean;canDelete:boolean}
export interface Repository{id:string;name:string;path:string;sourceType:RepositorySourceType;branch:string|null;commit:string|null;worktreeDigest:string|null;dirty:boolean;snapshotId:string|null;snapshotCreatedAt:string|null;codeGraphPath:string;codeGraphDetected:boolean;lastScannedAt:string|null;ownerAccountId:string;ownerDisplayName:string;relationship:'SUPER_ADMIN'|'OWNER'|'READ'|'MAINTAIN'|'MANAGE';ownershipVersion:number;repositoryStatus:string;capabilities:RepositoryCapabilities}
export interface RegisterRepositoryPayload{name:string;path:string}
export interface RescanRepositoryResponse{changed:boolean;repository:Repository}
export interface IndexJob{id:string;repositoryId:string;type:IndexJobType;status:IndexJobStatus;currentStep:string|null;errorMessage:string|null;startedAt:string|null;finishedAt:string|null;createdAt:string}
export interface CodeChunk{id:string;repositoryId:string;snapshotId:string;commitSha:string;filePath:string;symbolId:string|null;symbolName:string|null;symbolKind:string|null;language:string|null;chunkType:ChunkType;startLine:number|null;endLine:number|null;content:string;contentHash:string;createdAt:string}
export interface CodeChunkListResponse{total:number;limit:number;offset:number;chunks:CodeChunk[]}