package com.analyzercoder.application.intelligence;
import com.analyzercoder.infrastructure.persistence.mapper.IntelligenceMapper;import com.analyzercoder.infrastructure.persistence.model.KnowledgeCardRow;import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.security.*;import java.sql.Timestamp;import java.time.Instant;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class IntelligenceService{
private static final int DIM=64;private final IntelligenceMapper mapper;private final ObjectMapper json;public IntelligenceService(IntelligenceMapper mapper,ObjectMapper json){this.mapper=mapper;this.json=json;}
@Transactional public List<SearchHit> hybridSearch(UUID repoId,String query,int limit){ensureEmbeddings(repoId);return mapper.search(repoId,query,vector(query),Math.max(1,Math.min(limit,100))).stream().map(row->new SearchHit(uuid(row,"id"),uuid(row,"snapshot_id"),string(row,"file_path"),string(row,"symbol_name"),string(row,"symbol_kind"),integer(row,"start_line"),integer(row,"end_line"),string(row,"content"),string(row,"content_hash"),number(row,"score").doubleValue(),List.of("KEYWORD","SEMANTIC"))).toList();}
@Transactional public Answer ask(UUID repoId,UUID accountId,String question){List<SearchHit> hits=hybridSearch(repoId,question,6);UUID id=UUID.randomUUID(),snapshot=hits.isEmpty()?null:hits.get(0).snapshotId();String answer;if(hits.isEmpty())answer="当前仓库索引中没有找到足够证据。请先完成内容索引，或换一种更具体的描述。";else{StringBuilder b=new StringBuilder("根据当前快照中的代码证据，相关实现主要分布在：");for(int i=0;i<Math.min(3,hits.size());i++){SearchHit h=hits.get(i);b.append("\n").append(i+1).append(". ").append(h.filePath());if(h.symbolName()!=null)b.append(" 的 ").append(h.symbolName());b.append("（第 ").append(h.startLine()==null?"?":h.startLine()).append(" 行附近）");}answer=b.append("。回答由本地确定性检索生成；涉及行为判断时，请以引用源码为准。").toString();}mapper.insertConversation(id,repoId,accountId,question,answer,snapshot);List<Citation> citations=new ArrayList<>();for(int i=0;i<hits.size();i++){SearchHit h=hits.get(i);UUID cid=UUID.randomUUID();mapper.insertCitation(cid,id,h.chunkId(),h.filePath(),h.symbolName(),h.startLine(),h.endLine(),h.contentHash(),i+1);citations.add(new Citation(cid,h.chunkId(),h.filePath(),h.symbolName(),h.startLine(),h.endLine(),h.content(),i+1));}return new Answer(id,answer,snapshot,citations,"deterministic-local",Instant.now());}
@Transactional public GraphResult graph(UUID repoId,String symbol,int depth,String direction){rebuildGraph(repoId);int max=Math.max(1,Math.min(depth,5));List<GraphEdge> all=mapper.graphEdges(repoId).stream().map(row->new GraphEdge(string(row,"source_symbol"),string(row,"target_symbol"),string(row,"relation"))).toList();Map<String,Integer> distances=new LinkedHashMap<>();distances.put(symbol,0);List<GraphEdge> edges=new ArrayList<>();for(int d=0;d<max;d++)for(GraphEdge e:all){Integer from=distances.get(e.source()),to=distances.get(e.target());if(from!=null&&from==d&&!"UPSTREAM".equals(direction)){distances.putIfAbsent(e.target(),d+1);edges.add(e);}if(to!=null&&to==d&&!"DOWNSTREAM".equals(direction)){distances.putIfAbsent(e.source(),d+1);edges.add(e);}}List<GraphNode> nodes=distances.entrySet().stream().map(e->new GraphNode(e.getKey(),e.getValue(),e.getKey().equals(symbol))).toList();List<GraphEdge> unique=edges.stream().distinct().toList();return new GraphResult(nodes,unique,unique.size()>20?"HIGH":unique.size()>5?"MEDIUM":"LOW",List.of("静态关系不包含运行时反射与动态分派","结果绑定当前已发布快照"));}
public List<KnowledgeCard> cards(UUID repoId,boolean includeDraft){return mapper.cards(repoId,includeDraft).stream().map(IntelligenceService::card).toList();}
@Transactional public KnowledgeCard createCard(UUID repoId,UUID actor,CardInput in){UUID id=UUID.randomUUID();mapper.insertCard(id,repoId,actor,in.title(),in.cardType(),in.content(),in.tags().toArray(String[]::new),in.status());return findCard(repoId,id);}
@Transactional public KnowledgeCard updateCard(UUID repoId,UUID id,UUID actor,CardInput in){if(mapper.updateCard(id,repoId,actor,in.title(),in.cardType(),in.content(),in.tags().toArray(String[]::new),in.status())==0)throw new IllegalArgumentException("知识卡片不存在");return findCard(repoId,id);}private KnowledgeCard findCard(UUID repoId,UUID id){return cards(repoId,true).stream().filter(card->card.id().equals(id)).findFirst().orElseThrow();}
public Map<String,String> settings(){Map<String,String> out=new LinkedHashMap<>();for(Map<String,Object> row:mapper.settings())out.put(string(row,"setting_key"),string(row,"value"));return out;}@Transactional public Map<String,String> saveSettings(UUID actor,Map<String,String> values){values.forEach((key,value)->mapper.upsertSetting(key,value,actor));return settings();}
public List<BackupView> backups(){return mapper.backups().stream().map(row->new BackupView(uuid(row,"id"),string(row,"status"),string(row,"checksum"),instant(row.get("created_at")),instant(row.get("restored_at")))).toList();}
@Transactional public BackupView createBackup(UUID actor){Map<String,Object> manifest=new LinkedHashMap<>();manifest.put("format",1);manifest.put("createdAt",Instant.now().toString());manifest.put("settings",settings());manifest.put("knowledgeCards",mapper.backupKnowledge());manifest.put("repositories",mapper.backupRepositories());manifest.put("accounts",mapper.backupAccounts());try{String payload=json.writeValueAsString(manifest),checksum=sha256(payload);UUID id=UUID.randomUUID();mapper.insertBackup(id,payload,checksum,actor);return backups().stream().filter(backup->backup.id().equals(id)).findFirst().orElseThrow();}catch(JsonProcessingException e){throw new IllegalStateException("无法生成备份清单",e);}}
@Transactional public void restoreBackup(UUID id){String payload=mapper.backupManifest(id);if(payload==null)throw new IllegalArgumentException("备份不存在或不可恢复");String expected=mapper.backupChecksum(id);if(!sha256(payload).equals(expected))throw new IllegalStateException("备份校验失败");mapper.clearSessions();mapper.markRestored(id);}
private void ensureEmbeddings(UUID repoId){for(Map<String,Object> row:mapper.missingEmbeddings(repoId))mapper.upsertEmbedding(uuid(row,"id"),repoId,vector(string(row,"content")),string(row,"content_hash"));}
private void rebuildGraph(UUID repoId){mapper.deleteGraphEdges(repoId);List<Map<String,Object>> chunks=mapper.graphChunks(repoId);for(Map<String,Object> source:chunks)for(Map<String,Object> target:chunks){UUID sid=uuid(source,"id"),tid=uuid(target,"id");if(sid.equals(tid))continue;String name=string(target,"symbol_name");if(name!=null&&!name.isBlank()&&string(source,"content").contains(name+"("))mapper.insertGraphEdge(UUID.randomUUID(),repoId,uuid(source,"snapshot_id"),sid,tid,string(source,"symbol_name"),name);}}
private static KnowledgeCard card(KnowledgeCardRow row){return new KnowledgeCard(row.id(),row.repositoryId(),row.title(),row.cardType(),row.content(),List.of(row.tags()),row.status(),row.revision(),row.createdAt(),row.updatedAt());}private static Object value(Map<String,Object> row,String key){Object value=row.get(key);if(value==null)value=row.get(key.toUpperCase(Locale.ROOT));return value;}private static String string(Map<String,Object> row,String key){Object value=value(row,key);return value==null?null:String.valueOf(value);}private static UUID uuid(Map<String,Object> row,String key){Object value=value(row,key);return value==null?null:value instanceof UUID id?id:UUID.fromString(value.toString());}private static Integer integer(Map<String,Object> row,String key){Object value=value(row,key);return value==null?null:((Number)value).intValue();}private static Number number(Map<String,Object> row,String key){return(Number)value(row,key);}private static Instant instant(Object value){return value==null?null:value instanceof Instant i?i:((Timestamp)value).toInstant();}
private static String vector(String text){float[]out=new float[DIM];String s=text.toLowerCase(Locale.ROOT);for(int i=0;i<s.length();i++){int h=s.substring(i,Math.min(s.length(),i+3)).hashCode();out[Math.floorMod(h,DIM)]+=(h&1)==0?1:-1;}double norm=0;for(float x:out)norm+=x*x;norm=Math.sqrt(norm);StringBuilder b=new StringBuilder("[");for(int i=0;i<DIM;i++){if(i>0)b.append(',');b.append(norm==0?0:out[i]/norm);}return b.append(']').toString();}private static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
public record SearchHit(UUID chunkId,UUID snapshotId,String filePath,String symbolName,String symbolKind,Integer startLine,Integer endLine,String content,String contentHash,double score,List<String>channels){}public record Citation(UUID id,UUID chunkId,String filePath,String symbolName,Integer startLine,Integer endLine,String content,int rank){}public record Answer(UUID conversationId,String answer,UUID snapshotId,List<Citation>citations,String provider,Instant createdAt){}public record GraphNode(String symbol,int depth,boolean focus){}public record GraphEdge(String source,String target,String relation){}public record GraphResult(List<GraphNode>nodes,List<GraphEdge>edges,String risk,List<String>limitations){}public record CardInput(String title,String cardType,String content,List<String>tags,String status){public CardInput{if(tags==null)tags=List.of();if(status==null)status="DRAFT";}}public record KnowledgeCard(UUID id,UUID repositoryId,String title,String cardType,String content,List<String>tags,String status,int revision,Instant createdAt,Instant updatedAt){}public record BackupView(UUID id,String status,String checksum,Instant createdAt,Instant restoredAt){}
}