<script setup lang="ts">
import { Promotion } from '@element-plus/icons-vue';
import { computed, nextTick, shallowRef } from 'vue';
import { ElMessage } from 'element-plus';
import { intelligenceApi, type Answer } from '@/api/intelligence';
import { useRepositoryStore } from '@/stores/repositoryStore';
const repositories=useRepositoryStore(); const question=shallowRef(''); const busy=shallowRef(false); const messages=shallowRef<{role:'user'|'assistant';text:string;answer?:Answer}[]>([]);
const latest=computed(()=>[...messages.value].reverse().find(x=>x.answer)?.answer);
async function send(){const repoId=repositories.selectedRepositoryId;if(!repoId)return ElMessage.warning('请先选择仓库');if(!question.value.trim())return;const q=question.value.trim();messages.value=[...messages.value,{role:'user',text:q}];question.value='';busy.value=true;try{const answer=await intelligenceApi.ask(repoId,q);messages.value=[...messages.value,{role:'assistant',text:answer.answer,answer}];await nextTick();}catch(e){ElMessage.error(e instanceof Error?e.message:'问答失败');}finally{busy.value=false;}}
</script>
<template><section class="qa-page"><main class="chat-column"><div class="chat-head"><div><b>代码问答</b><span>本地混合检索，回答携带快照与行号引用</span></div><el-button @click="messages=[]">清空会话</el-button></div><div class="messages"><el-empty v-if="!messages.length" description="选择仓库后提出代码问题"/><article v-for="(m,i) in messages" :key="i" :class="['message',m.role]"><span>{{m.role==='user'?'你':'AI'}}</span><p style="white-space:pre-line">{{m.text}}</p><div v-if="m.answer" class="citations"><button v-for="c in m.answer.citations" :key="c.id">[{{c.rank}}] {{c.filePath}}:{{c.startLine}}</button></div></article></div><div class="composer"><el-input v-model="question" type="textarea" :autosize="{minRows:2,maxRows:4}" placeholder="询问当前代码库..." @keydown.ctrl.enter="send"/><el-button type="primary" :icon="Promotion" :loading="busy" circle @click="send"/></div></main><aside class="evidence qa-evidence"><div class="pane-head"><b>回答证据</b><span>{{latest?.citations.length??0}} 处引用</span></div><div v-for="c in latest?.citations" :key="c.id" class="evidence-block"><small>引用 {{c.rank}}</small><b>{{c.symbolName||c.filePath}}</b><p class="mono">{{c.filePath}} · L{{c.startLine}}-{{c.endLine}}</p><pre style="white-space:pre-wrap;max-height:180px;overflow:auto">{{c.content}}</pre></div></aside></section></template>
