import { effectScope, reactive } from 'vue';
import { beforeEach, expect, it, vi } from 'vitest';
import { createPinia, setActivePinia } from 'pinia';
import { useBranchContextStore } from '@/stores/branchContextStore';
import { useBranchReadScope } from './useBranchReadScope';
const repositories=reactive({ selectedRepositoryId:'p', selectedRepository:{sourceType:'LOCAL_GIT'} });
vi.mock('@/stores/repositoryStore',()=>({useRepositoryStore:()=>repositories}));
beforeEach(()=>{setActivePinia(createPinia());repositories.selectedRepository.sourceType='LOCAL_GIT';});
it('blocks Git reads until repository and selected branch match the pinned context',()=>{
  const branches=useBranchContextStore();
  const scope=effectScope();
  const reads=scope.run(useBranchReadScope)!;
  expect(reads.blocked.value).toBe(true);
  branches.selectedBranchId='b';
  branches.context={contextId:'ctx',repositoryId:'p',branchId:'b',branchName:'main',contentVersion:'s',commitSha:'a',expiresAt:''};
  expect(reads.blocked.value).toBe(false);
  branches.selectedBranchId='other';
  expect(reads.blocked.value).toBe(true);
  branches.context=null;
  branches.error='上下文失效';
  expect(reads.reason.value).toBe('上下文失效');
  scope.stop();
});
it('requires the WORKSPACE branch context for ZIP projects',()=>{
  repositories.selectedRepository.sourceType='ZIP';
  const scope=effectScope();
  const reads=scope.run(useBranchReadScope)!;
  expect(reads.requiresContext.value).toBe(true);
  expect(reads.blocked.value).toBe(true);
  const branches=useBranchContextStore();
  branches.selectedBranchId='workspace';
  branches.context={contextId:'ctx',repositoryId:'p',branchId:'workspace',branchName:'WORKSPACE',contentVersion:'v',commitSha:'c',expiresAt:''};
  expect(reads.blocked.value).toBe(false);
  scope.stop();
});
